# -*- coding: utf-8 -*-
"""lab 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DjxeI6kaR3dNpVbRIY1MNUKNULTYjUaA

**Lab**- 7
"""

!pip install transformers datasets accelerate

from datasets import load_dataset
from transformers import (AutoTokenizer,
                          AutoModelForSequenceClassification,
                          TrainingArguments,
                          Trainer,
                          DataCollatorWithPadding)

# ✅ Load small subset (IMPORTANT)
dataset = load_dataset("imdb")

train_dataset = dataset["train"].shuffle(seed=42).select(range(2000))
test_dataset = dataset["test"].shuffle(seed=42).select(range(500))

# ✅ Use smaller tokenizer/model
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def tokenize(example):
    return tokenizer(example["text"], truncation=True, max_length=128)

train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

# ✅ Dynamic padding (saves RAM)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# ✅ Load lightweight model
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased", num_labels=2
)

# ✅ Training settings (low RAM)
training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=1,
    logging_steps=50,
    save_strategy="no",
    fp16=True  # if GPU available
)

# ✅ Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=data_collator,
)

trainer.train()

print("✅ Training Completed")